kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven
    commands:
      - mvn clean package
  - name: deploy to DockerHub
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: selfmaderulez/studienprojekt-hse-pakn
      tags: [latest, 1.0.0]