kind: pipeline
type: docker
name: frontend

steps:
  - name: deploy frontend to DockerHub
    image: plugins/docker
    settings:
      context: frontend
      dockerfile: frontend/Dockerfile
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: selfmaderulez/studienprojekt-hse-pakn-frontend
      tags: [latest, 1.0.0]

---
kind: pipeline
type: docker
name: backend

steps:
  - name: build backend
    image: maven
    commands:
      - mvn clean package
  - name: deploy backend to DockerHub
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: selfmaderulez/studienprojekt-hse-pakn
      tags: [latest, 1.0.0]
      
---
kind: pipeline
type: docker
name: deployment

steps:
- name: deploy
  image: docker
  environment:
    DRONE_SECRET_DB_USER: 
      from_secret: db_user
    DRONE_SECRET_DB_PASS:
      from_secret: db_pass
    DRONE_SECRET_DB_HOST:
      from_secret: db_host
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock

  when:
    event:
    - promote
    target:
    - production
    
  commands:
    - docker compose up -d
    
depends_on:
- frontend
- backend

volumes:
  - name: docker-socket
    host: 
      path: /var/run/docker.sock
