kind: pipeline
type: docker
name: frontend

steps:
  - name: deploy frontend to DockerHub
    image: plugins/docker
    settings:
      context: ./frontend
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: selfmaderulez/studienprojekt-hse-pakn-frontend
      tags: [latest, 1.0.0]

---
kind: pipeline
type: docker
name: backend

  - name: build backend
    image: maven
    commands:
      - mvn clean package
  - name: deploy backend to DockerHub
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: selfmaderulez/studienprojekt-hse-pakn
      tags: [latest, 1.0.0]