kind: pipeline
type: docker
name: default

steps:
  - name: build frontend
    image: node
    commands:
      - cd frontend
      - npm install
      - npm run build
      - npm run export
  - name: move frontend
    image: alpine
    commands:
      - mkdir /drone/src/src/main/resources/static
      - mv /drone/src/frontend/out/* /drone/src/src/main/resources/static/
  - name: build backend
    image: maven
    commands:
      - mvn clean package
  - name: deploy to DockerHub
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: selfmaderulez/studienprojekt-hse-pakn
      tags: [latest, 1.0.0]